const COMMANDS = [
  // pre-fire go poll
  "GO_POLL_TOGGLE_SAFETY_OFFICER_1",
  "GO_POLL_TOGGLE_SAFETY_OFFICER_2",
  "GO_POLL_TOGGLE_ADVISER",
  "GO_POLL_TOGGLE_PROP_LEAD",
  "GO_POLL_TOGGLE_ELEC_LEAD",
  // standby pre-fill checklist
  "PRE_FILL_CHECKLIST_TOGGLE_FILL_RELAY",
  "PRE_FILL_CHECKLIST_TOGGLE_ABORT_RELAY",
  "PRE_FILL_CHECKLIST_TOGGLE_FIRE_RELAY",
  "PRE_FILL_CHECKLIST_TOGGLE_FILL_SOLENOID",
  "PRE_FILL_CHECKLIST_TOGGLE_ABORT_SOLENOID",
  "PRE_FILL_CHECKLIST_TOGGLE_WET_GROUND",
  "PRE_FILL_CHECKLIST_TOGGLE_OPEN_TANK",
  // standby state selection
  "STANDBY_STATE_ACTIVATE_STANDBY",
  "STANDBY_STATE_ACTIVATE_KEEP",
  "STANDBY_STATE_ACTIVATE_FILL",
  "STANDBY_STATE_ACTIVATE_PURGE",
  "STANDBY_STATE_ACTIVATE_PULSE",
  // standby mode to launch mode
  "GO_TO_LAUNCH_MODE",
  // launch mode command center
  "LAUNCH_MODE_COMMAND_CENTER_EXECUTE_KEEP",
  "LAUNCH_MODE_COMMAND_CENTER_STOP_KEEP",
  "LAUNCH_MODE_COMMAND_CENTER_EXECUTE_ARM",
  "LAUNCH_MODE_COMMAND_CENTER_STOP_ARM",
  "LAUNCH_MODE_COMMAND_CENTER_EXECUTE_FIRE",
  "LAUNCH_MODE_COMMAND_CENTER_STOP_FIRE",
  // launch mode abort control
  "LAUNCH_MODE_ABORT_CONTROL_EXECUTE_ARM",
  "LAUNCH_MODE_ABORT_CONTROL_STOP_ARM",
  "LAUNCH_MODE_ABORT_CONTROL_EXECUTE_ABORT",
  "LAUNCH_MODE_ABORT_CONTROL_STOP_ABORT",
  // launch mode to recovery mode
  "GO_TO_RECOVERY_MODE",
  // recovery visual contact confirmation
  "CONFIRM_VISUAL_CONTACT",
  // recovery range permit
  "RANGE_PERMIT_TOGGLE_SAFETY_OFFICER_1",
  "RANGE_PERMIT_TOGGLE_SAFETY_OFFICER_2",
  "RANGE_PERMIT_TOGGLE_ADVISER",
] as const;

export type Command = (typeof COMMANDS)[number];

export function isValidCommand(value: unknown): value is Command {
  return COMMANDS.includes(value as Command);
}
